### ISSUE TITLE
Add payment description method in email template

### ISSUE THREAD

**Issue by griccitiello** [magespecialist/MSP_CashOnDelivery#13]
Hello,

I am trying to add the cash on delivery description in my email template.
This is the code I am trying with, but does not work.

```
{{var order.payment.method_instance.description}}
or
{{var order.getPayment().getMethodInstance().getDescription()}}

```

Thanks, any help appreciated!

**Comment by griccitiello** [comment]
I've just tried with this one too
`getCodDescription()`

any help appreciated, thanks!

**Comment by phoenix128** [comment]
This should work:
{{var order.getPayment().getMethodInstance().getTitle()}}

**Comment by griccitiello** [comment]
Hello, thanks for your reply.
Yes it works like a charm for the title, but I am trying to add the description text in my email template.
![configurazione](https://cloud.githubusercontent.com/assets/10668598/15115979/bdf149ee-1601-11e6-8ac1-5e67901fafe2.png)

Thanks for your help!

**Comment by phoenix128** [comment]
You said you tried "getCodDescription()", make sure you syntax was the following:

{{var order.getPayment().getMethodInstance().getCodDescription()}}

It should work.

**Comment by griccitiello** [comment]
Yeah i've tried it in my environment, but does not work .
I can only print the title.

I will try in a fresh magento installation too, but looks like something missing.

**Comment by andreasacca** [comment]
Hi RIccardo,
I changed {{var payment_html}} with your code:
{{var order.getPayment().getMethodInstance().getTitle()}}

and it worked.

Thank you.

Magento 1.9.2.4
