### ISSUE TITLE
Settaggio Locale e Estero

### ISSUE THREAD

**Issue by Yavonz15** [magespecialist/MSP_CashOnDelivery#20]
Dove capisce se è estero o locale?

Se imposto da system->configuration->sales

5 locale
5 estero

mi stampa sempre 10€ il costo di contrassegno

**Comment by phoenix128** [comment]
Ciao @Yavonz15 ,
dipende dal paese di spedizione, ovvero se questo è diverso dal paese impostato per lo store nel backend.
