### ISSUE TITLE
Wiki pages

### ISSUE THREAD

**Issue by giuseppemorelli** [magespecialist/MSP_CashOnDelivery#5]
Hi!
You can use this page to get main informations about composer and modman
https://github.com/magemindcom/Aoe_TemplateHints/wiki/Magento-Installation

Hope can help you!

**Comment by midimarcus** [comment]
Very appreciated!
Here is the page:
https://github.com/magespecialist/MSP_CashOnDelivery/wiki/Extension-installation-via-Composer-Modman
with your credits in footer.
Thanks.

**Comment by giuseppemorelli** [comment]
Hi Marco,
I have suggest the page, but needs to be changed with your extension specifics.

Change the part of composer.json with this:


```
{
    ...
    "require": {
        "magento-hackathon/magento-composer-installer": "*",
        "magespecialist/msp_cashondelivery": "1.2.5"
    },
    ....
    "repositories": [
        {
            "type": "vcs",
            "url": "git@github.com:magespecialist/MSP_CashOnDelivery.git"
        }
    ],
    .....
}
```

**Comment by midimarcus** [comment]
Sorry,
my fault this time!
