### ISSUE TITLE
Tax Calculation Bug (makes the extension non-usable)

### ISSUE THREAD

**Issue by Webmasterei** [magespecialist/MSP_CashOnDelivery#7]
Hi there,
on Mage 1.9.2 the extension has a problem.

The Price caclulates with 4,- € (incl. Tax correctly) 
1. Bug: the netprice is shown below tax. It should be the incl. price.
2. Bug: the price is not included into the invoice calculation

See Screenshots:
![auswahl_023](https://cloud.githubusercontent.com/assets/6458728/8721533/ac9fe85c-2bbb-11e5-9a06-d4f80489650a.png)
![auswahl_024](https://cloud.githubusercontent.com/assets/6458728/8721535/aed14ee0-2bbb-11e5-874d-4ccc008ec46a.png)

**Comment by midimarcus** [comment]
Thank you for report, we'll give it a look.

**Comment by possi** [comment]
+1 Have the same Issue with 1.9.2.4
(Fun-Fact. Problem also affects https://github.com/PHOENIX-MEDIA/Magento-CashOnDelivery)

**Comment by possi** [comment]
What I can tell from my debugging: It is a Mage-Core-Bug and shouldn't be workaround withing this Extension.
Processing afters and befores of general/sales/quote/totals fails depending of the count of entries.
Mage_Sales_Model_Config_Ordered::_getSortedCollectorCodes abuses PHPs uasort for processing, which uses Quicksort-Algorhytm. Mage_Sales_Model_Config_Ordered::_compareTotals states some totals as "equal" when there order doesn't matter. All entries that are equal to one specific entry, are considered equal to.

Failing Example:
- tax_subtotal <=> wee returns 0
- subtotal <=> wee returns 0
- Therefore tax_subtotal <=> subtotal is considered equal to, if the order doesn't matter quicksort may puts tax_subtotal before subtotal.

**Comment by possi** [comment]
My Magento-Bug: https://www.magentocommerce.com/bug-tracking/issue/index/id/1451
